include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: warning
  language:
    strict-casts: false
    strict-raw-types: false

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_interpolation_to_compose_strings: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    avoid_redundant_argument_values: true
    sized_box_for_whitespace: true
    use_decorated_box: true
